<a href="https://colab.research.google.com/github/YashPatel1604/AI-workshop-UTD/blob/main/Additional_excercise_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = a.flat[3]
print(b)

4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Additional excercise

###Create a 2d array, sort the array by a given row

In [ ]:
# your code goes here
x = np.random.rand(2,4)
print(x)
x.sort(axis=1)
print(x)

[[0.5016742  0.11856792 0.72118048 0.73560206]
 [0.72007352 0.78811628 0.36443308 0.43161247]]
[[0.11856792 0.5016742  0.72118048 0.73560206]
 [0.36443308 0.43161247 0.72007352 0.78811628]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Delete a particular row from an array

In [ ]:
# your code goes here
x = np.random.rand(2,4)
print(x)
np.delete(x,1,axis=0)

[[0.52689731 0.92294477 0.94145333 0.80958246]
 [0.12621345 0.7112124  0.44078862 0.41745674]]


array([[0.52689731, 0.92294477, 0.94145333, 0.80958246]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 5 by 5 matrix and print the values 1,2,3,4 just below the diagnol

In [ ]:
'''

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

'''
x = np.diag([1,2,3,4],k=-1)
print(x)
# your code goes here


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

