<a href="https://colab.research.google.com/github/YashPatel1604/AI-workshop-UTD/blob/main/More_on_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10,23,size = (4,4))

print(a)

b = a[::-1,::-1]
print(b)

b[0][0] = -1221
print("After a:", a)

[[21 12 16 14]
 [22 21 11 21]
 [18 11 19 20]
 [17 11 13 17]]
[[17 13 11 17]
 [20 19 11 18]
 [21 11 21 22]
 [14 16 12 21]]
After a: [[   21    12    16    14]
 [   22    21    11    21]
 [   18    11    19    20]
 [   17    11    13 -1221]]


In [ ]:
c = a.copy()
print(c)
c[0][0]=1

[[   21    12    16    14]
 [   22    21    11    21]
 [   18    11    19    20]
 [   17    11    13 -1221]]


In [ ]:
z = np.arange(10)
print(z)
z[z<z.mean()] = -1
print(z)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1 -1  5  6  7  8  9]


In [ ]:
print(a)

[[   21    12    16    14]
 [   22    21    11    21]
 [   18    11    19    20]
 [   17    11    13 -1221]]


In [ ]:
print(a+b)

[[-1200    25    27    31]
 [   42    40    22    39]
 [   39    22    40    42]
 [   31    27    25 -1200]]


In [ ]:
print(a-b)

[[ 1242    -1     5    -3]
 [    2     2     0     3]
 [   -3     0    -2    -2]
 [    3    -5     1 -1242]]


In [ ]:
print(a*b)

[[-25641    156    176    238]
 [   440    399    121    378]
 [   378    121    399    440]
 [   238    176    156 -25641]]


In [ ]:
print(a%b)

[[-1200    12     5    14]
 [    2     2     0     3]
 [   18     0    19    20]
 [    3    11     1    18]]


In [ ]:
print(a.T)

[[   21    22    18    17]
 [   12    21    11    11]
 [   16    11    19    13]
 [   14    21    20 -1221]]


In [ ]:
print(a)

[[   21    12    16    14]
 [   22    21    11    21]
 [   18    11    19    20]
 [   17    11    13 -1221]]


In [ ]:
a = np.random.randint(10,80,size=(3,2))
b = np.random.randint(10,80,size=(2,3))

In [ ]:
print(a)
print(b)

[[66 51]
 [71 42]
 [22 55]]
[[70 47 53]
 [46 74 67]]


In [ ]:
print(a.dot(b))
print(b.dot(a))

[[6966 6876 6915]
 [6902 6445 6577]
 [4070 5104 4851]]
[[9123 8459]
 [9764 9139]]


In [ ]:
print(a@b)
print(b@a)

[[6966 6876 6915]
 [6902 6445 6577]
 [4070 5104 4851]]
[[9123 8459]
 [9764 9139]]


In [ ]:
print(np.matmul(a,b))

[[6966 6876 6915]
 [6902 6445 6577]
 [4070 5104 4851]]
